--
-- PostgreSQL database dump
--

\restrict sjw8gaiQvPMjQ3UzYmeCWsPJv4Sp6Z7An4euLAFCkWAiStZsSdaa7l9vT4Oh2ke

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: academic_evaluations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.academic_evaluations (
    evaluationid bigint NOT NULL,
    course_comment text,
    course_score integer NOT NULL,
    evaluation_date timestamp(6) without time zone NOT NULL,
    instructor_comment text,
    instructor_score integer NOT NULL,
    course_id bigint NOT NULL,
    user_id bigint
);


--
-- Name: academic_evaluations_evaluationid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.academic_evaluations ALTER COLUMN evaluationid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academic_evaluations_evaluationid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_course_stats_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_course_stats_history (
    id bigint NOT NULL,
    course_id bigint NOT NULL,
    snapshot_year integer NOT NULL,
    active_students_in_course integer NOT NULL,
    course_average_progress_percentage integer CONSTRAINT admin_course_stats_history_course_average_progress_per_not_null NOT NULL,
    approval_index_percentage integer NOT NULL,
    average_course_rating double precision,
    average_instructor_rating double precision,
    average_grade double precision,
    average_work_grade double precision,
    average_final_exam_grade double precision,
    real_data boolean DEFAULT false NOT NULL,
    generated_at timestamp without time zone DEFAULT now() NOT NULL,
    activestudentsincourse integer NOT NULL,
    approvalindexpercentage integer NOT NULL,
    averagecourserating double precision,
    averagefinalexamgrade double precision,
    averagegrade double precision,
    averageinstructorrating double precision,
    averageworkgrade double precision,
    courseaverageprogresspercentage integer CONSTRAINT admin_course_stats_history_courseaverageprogresspercen_not_null NOT NULL,
    generatedat timestamp(6) without time zone,
    realdata boolean NOT NULL
);


--
-- Name: admin_course_stats_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.admin_course_stats_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: admin_course_stats_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.admin_course_stats_history_id_seq OWNED BY public.admin_course_stats_history.id;


--
-- Name: admin_global_stats_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_global_stats_history (
    id bigint NOT NULL,
    snapshot_year integer NOT NULL,
    total_students integer NOT NULL,
    total_professors integer NOT NULL,
    top_course_enrollment integer NOT NULL,
    real_data boolean DEFAULT false NOT NULL,
    generated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: admin_global_stats_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.admin_global_stats_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: admin_global_stats_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.admin_global_stats_history_id_seq OWNED BY public.admin_global_stats_history.id;


--
-- Name: admin_global_top_course_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_global_top_course_history (
    id bigint NOT NULL,
    history_id bigint NOT NULL,
    rank_position integer NOT NULL,
    course_id bigint,
    course_title character varying(255) NOT NULL,
    enrolled_students integer NOT NULL
);


--
-- Name: admin_global_top_course_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.admin_global_top_course_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: admin_global_top_course_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.admin_global_top_course_history_id_seq OWNED BY public.admin_global_top_course_history.id;


--
-- Name: auth_refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_refresh_tokens (
    token_id bigint NOT NULL,
    user_id bigint NOT NULL,
    token_hash character varying(128) NOT NULL,
    jti character varying(64) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    is_revoked boolean DEFAULT false NOT NULL,
    replaced_by_token_id bigint,
    last_used_at timestamp without time zone,
    revoked_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    tokenid bigint NOT NULL
);


--
-- Name: auth_refresh_tokens_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.auth_refresh_tokens_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: auth_refresh_tokens_token_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.auth_refresh_tokens_token_id_seq OWNED BY public.auth_refresh_tokens.token_id;


--
-- Name: auth_refresh_tokens_tokenid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_refresh_tokens ALTER COLUMN tokenid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_refresh_tokens_tokenid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_grades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_grades (
    grade_id bigint NOT NULL,
    score numeric(10,2) NOT NULL,
    title character varying(255) NOT NULL,
    enrollment_id bigint NOT NULL,
    feedback text,
    comments text
);


--
-- Name: course_grades_grade_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_grades ALTER COLUMN grade_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_grades_grade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_material_dispatch_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_material_dispatch_config (
    config_id bigint NOT NULL,
    course_id bigint NOT NULL,
    dispatch_parts integer NOT NULL,
    exam_threshold numeric(5,2) DEFAULT 90.00 NOT NULL,
    created_by_user_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    configid bigint NOT NULL
);


--
-- Name: course_material_dispatch_config_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.course_material_dispatch_config_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: course_material_dispatch_config_config_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.course_material_dispatch_config_config_id_seq OWNED BY public.course_material_dispatch_config.config_id;


--
-- Name: course_material_dispatch_config_configid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_material_dispatch_config ALTER COLUMN configid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_material_dispatch_config_configid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses (
    course_id bigint NOT NULL,
    category character varying(255),
    course_type character varying(255),
    duration real,
    instructors text,
    language character varying(255),
    "num of viewers" integer,
    rating real,
    short_intro text,
    site character varying(255),
    skills text,
    "sub-category" character varying(255),
    subtitle_languages text,
    title character varying(255),
    url text,
    assigned_user_id bigint,
    title_key character varying(255),
    ever_used boolean DEFAULT false NOT NULL,
    num_of_viewers integer,
    sub_category character varying(255)
);


--
-- Name: courses_course_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses ALTER COLUMN course_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_metadata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_metadata (
    documentid bigint NOT NULL,
    filename character varying(255) NOT NULL,
    originalname character varying(255) NOT NULL,
    upload_date timestamp(6) without time zone NOT NULL,
    user_id bigint,
    folder_type character varying(255) NOT NULL,
    course_id bigint,
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    evaluation_type character varying(255),
    is_read boolean DEFAULT false,
    hidden_for_sender boolean DEFAULT false NOT NULL,
    hidden_for_receiver boolean DEFAULT false NOT NULL,
    CONSTRAINT document_metadata_folder_type_check CHECK (((folder_type)::text = ANY ((ARRAY['SENT'::character varying, 'RECEIVED'::character varying])::text[])))
);


--
-- Name: document_metadata_documentid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.document_metadata ALTER COLUMN documentid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_metadata_documentid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: enrollment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.enrollment (
    enrollmentid bigint NOT NULL,
    enrolled_at timestamp(6) without time zone NOT NULL,
    progress integer NOT NULL,
    status character varying(255) NOT NULL,
    course_id bigint,
    user_id bigint,
    started_at timestamp(6) without time zone,
    progress_alert_student_ack boolean DEFAULT false NOT NULL,
    progress_alert_professor_ack boolean DEFAULT false NOT NULL
);


--
-- Name: enrollment_enrollmentid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.enrollment ALTER COLUMN enrollmentid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enrollment_enrollmentid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interest_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interest_categories (
    interest_id bigint NOT NULL,
    category character varying(255)
);


--
-- Name: interest_course_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interest_course_types (
    interest_id bigint NOT NULL,
    course_type character varying(255)
);


--
-- Name: interest_durations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interest_durations (
    interest_id bigint NOT NULL,
    duration character varying(255)
);


--
-- Name: interest_languages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interest_languages (
    interest_id bigint NOT NULL,
    language character varying(255)
);


--
-- Name: interest_subtitle_languages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interest_subtitle_languages (
    interest_id bigint NOT NULL,
    subtitle_languages character varying(255),
    subtitle_language character varying(255)
);


--
-- Name: interests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interests (
    user_id bigint NOT NULL
);


--
-- Name: professor_course_alerts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.professor_course_alerts (
    alert_id bigint NOT NULL,
    professor_user_id bigint NOT NULL,
    student_user_id bigint NOT NULL,
    course_id bigint NOT NULL,
    enrollment_id bigint NOT NULL,
    alert_type character varying(32) NOT NULL,
    checkpoint_index integer NOT NULL,
    checkpoint_percent numeric(5,2) NOT NULL,
    status character varying(16) DEFAULT 'PENDING'::character varying NOT NULL,
    bell_dismissed boolean DEFAULT false NOT NULL,
    title character varying(180) NOT NULL,
    message character varying(600) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    alertid bigint NOT NULL
);


--
-- Name: professor_course_alerts_alert_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.professor_course_alerts_alert_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: professor_course_alerts_alert_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.professor_course_alerts_alert_id_seq OWNED BY public.professor_course_alerts.alert_id;


--
-- Name: professor_course_alerts_alertid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.professor_course_alerts ALTER COLUMN alertid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.professor_course_alerts_alertid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_profiles (
    user_id bigint NOT NULL,
    avatar_path character varying(512),
    phone_number character varying(20),
    home_address character varying(255)
);


--
-- Name: user_system_notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_system_notifications (
    notificationid bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    message character varying(600) NOT NULL,
    is_read boolean NOT NULL,
    redirecturl character varying(200) NOT NULL,
    title character varying(160) NOT NULL,
    type character varying(64) NOT NULL,
    receiver_user_id bigint NOT NULL,
    related_course_id bigint
);


--
-- Name: user_system_notifications_notificationid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_system_notifications ALTER COLUMN notificationid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_system_notifications_notificationid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    email character varying(255),
    enabled boolean DEFAULT true NOT NULL,
    failed_login_attempts integer DEFAULT 0 NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'PROFESSOR'::character varying, 'STUDENT'::character varying])::text[])))
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_course_stats_history id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_course_stats_history ALTER COLUMN id SET DEFAULT nextval('public.admin_course_stats_history_id_seq'::regclass);


--
-- Name: admin_global_stats_history id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_global_stats_history ALTER COLUMN id SET DEFAULT nextval('public.admin_global_stats_history_id_seq'::regclass);


--
-- Name: admin_global_top_course_history id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_global_top_course_history ALTER COLUMN id SET DEFAULT nextval('public.admin_global_top_course_history_id_seq'::regclass);


--
-- Name: auth_refresh_tokens token_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_refresh_tokens ALTER COLUMN token_id SET DEFAULT nextval('public.auth_refresh_tokens_token_id_seq'::regclass);


--
-- Name: course_material_dispatch_config config_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_material_dispatch_config ALTER COLUMN config_id SET DEFAULT nextval('public.course_material_dispatch_config_config_id_seq'::regclass);


--
-- Name: professor_course_alerts alert_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.professor_course_alerts ALTER COLUMN alert_id SET DEFAULT nextval('public.professor_course_alerts_alert_id_seq'::regclass);


--
-- Name: academic_evaluations academic_evaluations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_evaluations
    ADD CONSTRAINT academic_evaluations_pkey PRIMARY KEY (evaluationid);


--
-- Name: admin_course_stats_history admin_course_stats_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_course_stats_history
    ADD CONSTRAINT admin_course_stats_history_pkey PRIMARY KEY (id);


--
-- Name: admin_global_stats_history admin_global_stats_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_global_stats_history
    ADD CONSTRAINT admin_global_stats_history_pkey PRIMARY KEY (id);


--
-- Name: admin_global_stats_history admin_global_stats_history_snapshot_year_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_global_stats_history
    ADD CONSTRAINT admin_global_stats_history_snapshot_year_key UNIQUE (snapshot_year);


--
-- Name: admin_global_top_course_history admin_global_top_course_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_global_top_course_history
    ADD CONSTRAINT admin_global_top_course_history_pkey PRIMARY KEY (id);


--
-- Name: auth_refresh_tokens auth_refresh_tokens_jti_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_refresh_tokens
    ADD CONSTRAINT auth_refresh_tokens_jti_key UNIQUE (jti);


--
-- Name: auth_refresh_tokens auth_refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_refresh_tokens
    ADD CONSTRAINT auth_refresh_tokens_pkey PRIMARY KEY (token_id);


--
-- Name: auth_refresh_tokens auth_refresh_tokens_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_refresh_tokens
    ADD CONSTRAINT auth_refresh_tokens_token_hash_key UNIQUE (token_hash);


--
-- Name: course_grades course_grades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_grades
    ADD CONSTRAINT course_grades_pkey PRIMARY KEY (grade_id);


--
-- Name: course_material_dispatch_config course_material_dispatch_config_course_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_material_dispatch_config
    ADD CONSTRAINT course_material_dispatch_config_course_id_key UNIQUE (course_id);


--
-- Name: course_material_dispatch_config course_material_dispatch_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_material_dispatch_config
    ADD CONSTRAINT course_material_dispatch_config_pkey PRIMARY KEY (config_id);


--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (course_id);


--
-- Name: document_metadata document_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_metadata
    ADD CONSTRAINT document_metadata_pkey PRIMARY KEY (documentid);


--
-- Name: enrollment enrollment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollment
    ADD CONSTRAINT enrollment_pkey PRIMARY KEY (enrollmentid);


--
-- Name: interests interests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interests
    ADD CONSTRAINT interests_pkey PRIMARY KEY (user_id);


--
-- Name: professor_course_alerts professor_course_alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.professor_course_alerts
    ADD CONSTRAINT professor_course_alerts_pkey PRIMARY KEY (alert_id);


--
-- Name: admin_course_stats_history uk_admin_course_stats_history_course_year; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_course_stats_history
    ADD CONSTRAINT uk_admin_course_stats_history_course_year UNIQUE (course_id, snapshot_year);


--
-- Name: professor_course_alerts uk_prof_alert_enrollment_type_checkpoint; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.professor_course_alerts
    ADD CONSTRAINT uk_prof_alert_enrollment_type_checkpoint UNIQUE (enrollment_id, alert_type, checkpoint_index);


--
-- Name: academic_evaluations ukfd91kr3irmimo7r3iebptlls4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_evaluations
    ADD CONSTRAINT ukfd91kr3irmimo7r3iebptlls4 UNIQUE (user_id, course_id);


--
-- Name: admin_course_stats_history ukjnva07jupikd9fy4ajsorl8ec; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_course_stats_history
    ADD CONSTRAINT ukjnva07jupikd9fy4ajsorl8ec UNIQUE (course_id, snapshot_year);


--
-- Name: user_profiles user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (user_id);


--
-- Name: user_system_notifications user_system_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_system_notifications
    ADD CONSTRAINT user_system_notifications_pkey PRIMARY KEY (notificationid);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: idx_auth_refresh_tokens_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_refresh_tokens_expires_at ON public.auth_refresh_tokens USING btree (expires_at);


--
-- Name: idx_auth_refresh_tokens_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_refresh_tokens_user_id ON public.auth_refresh_tokens USING btree (user_id);


--
-- Name: idx_courses_category_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_courses_category_trgm ON public.courses USING gin (category public.gin_trgm_ops);


--
-- Name: idx_courses_title_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_courses_title_key ON public.courses USING btree (title_key);


--
-- Name: idx_courses_title_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_courses_title_trgm ON public.courses USING gin (title public.gin_trgm_ops);


--
-- Name: idx_prof_alert_professor_bell; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_prof_alert_professor_bell ON public.professor_course_alerts USING btree (professor_user_id, bell_dismissed, created_at);


--
-- Name: idx_prof_alert_professor_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_prof_alert_professor_created ON public.professor_course_alerts USING btree (professor_user_id, created_at DESC);


--
-- Name: uk_user_notification_recommendation_course; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_user_notification_recommendation_course ON public.user_system_notifications USING btree (receiver_user_id, type, related_course_id) WHERE (((type)::text = 'COURSE_RECOMMENDATION'::text) AND (related_course_id IS NOT NULL));


--
-- Name: admin_course_stats_history admin_course_stats_history_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_course_stats_history
    ADD CONSTRAINT admin_course_stats_history_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(course_id);


--
-- Name: enrollment fk4x08no2mpupkr616h50w3aksx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollment
    ADD CONSTRAINT fk4x08no2mpupkr616h50w3aksx FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: user_system_notifications fk5abqrujr7b5a9kikq0thrydt3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_system_notifications
    ADD CONSTRAINT fk5abqrujr7b5a9kikq0thrydt3 FOREIGN KEY (receiver_user_id) REFERENCES public.users(user_id);


--
-- Name: academic_evaluations fk6x42py07igruh1qbux9la2ibh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_evaluations
    ADD CONSTRAINT fk6x42py07igruh1qbux9la2ibh FOREIGN KEY (course_id) REFERENCES public.courses(course_id);


--
-- Name: enrollment fk7ofybdo2o0ngc4de3uvx4dxqv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollment
    ADD CONSTRAINT fk7ofybdo2o0ngc4de3uvx4dxqv FOREIGN KEY (course_id) REFERENCES public.courses(course_id);


--
-- Name: interest_categories fk7ukm8esuwxq96jrhsx9cff488; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interest_categories
    ADD CONSTRAINT fk7ukm8esuwxq96jrhsx9cff488 FOREIGN KEY (interest_id) REFERENCES public.interests(user_id);


--
-- Name: admin_global_top_course_history fk_admin_global_top_course_history_history; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_global_top_course_history
    ADD CONSTRAINT fk_admin_global_top_course_history_history FOREIGN KEY (history_id) REFERENCES public.admin_global_stats_history(id) ON DELETE CASCADE;


--
-- Name: auth_refresh_tokens fk_auth_refresh_tokens_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_refresh_tokens
    ADD CONSTRAINT fk_auth_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: courses fk_courses_assigned_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk_courses_assigned_user FOREIGN KEY (assigned_user_id) REFERENCES public.users(user_id);


--
-- Name: course_material_dispatch_config fk_dispatch_config_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_material_dispatch_config
    ADD CONSTRAINT fk_dispatch_config_course FOREIGN KEY (course_id) REFERENCES public.courses(course_id) ON DELETE CASCADE;


--
-- Name: course_material_dispatch_config fk_dispatch_config_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_material_dispatch_config
    ADD CONSTRAINT fk_dispatch_config_user FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id) ON DELETE RESTRICT;


--
-- Name: professor_course_alerts fk_prof_alert_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.professor_course_alerts
    ADD CONSTRAINT fk_prof_alert_course FOREIGN KEY (course_id) REFERENCES public.courses(course_id) ON DELETE CASCADE;


--
-- Name: professor_course_alerts fk_prof_alert_enrollment; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.professor_course_alerts
    ADD CONSTRAINT fk_prof_alert_enrollment FOREIGN KEY (enrollment_id) REFERENCES public.enrollment(enrollmentid) ON DELETE CASCADE;


--
-- Name: professor_course_alerts fk_prof_alert_professor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.professor_course_alerts
    ADD CONSTRAINT fk_prof_alert_professor FOREIGN KEY (professor_user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: professor_course_alerts fk_prof_alert_student; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.professor_course_alerts
    ADD CONSTRAINT fk_prof_alert_student FOREIGN KEY (student_user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: user_profiles fk_user_profile_users; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT fk_user_profile_users FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: interest_durations fkavalw5c36qyb1f3cko9eorqjh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interest_durations
    ADD CONSTRAINT fkavalw5c36qyb1f3cko9eorqjh FOREIGN KEY (interest_id) REFERENCES public.interests(user_id);


--
-- Name: academic_evaluations fkcdvpekegquirhbeoxlg50ckcf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_evaluations
    ADD CONSTRAINT fkcdvpekegquirhbeoxlg50ckcf FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: document_metadata fkcv3ohi99l8qjbl6h2wiqqfc1c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_metadata
    ADD CONSTRAINT fkcv3ohi99l8qjbl6h2wiqqfc1c FOREIGN KEY (receiver_id) REFERENCES public.users(user_id);


--
-- Name: interest_course_types fkdhe6af62aw27c3vpyv8w884fg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interest_course_types
    ADD CONSTRAINT fkdhe6af62aw27c3vpyv8w884fg FOREIGN KEY (interest_id) REFERENCES public.interests(user_id);


--
-- Name: interest_subtitle_languages fkiaqwxlocybnn7oy9i47jyh438; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interest_subtitle_languages
    ADD CONSTRAINT fkiaqwxlocybnn7oy9i47jyh438 FOREIGN KEY (interest_id) REFERENCES public.interests(user_id);


--
-- Name: document_metadata fkix6xjw02keyr8loayd8bo42bm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_metadata
    ADD CONSTRAINT fkix6xjw02keyr8loayd8bo42bm FOREIGN KEY (sender_id) REFERENCES public.users(user_id);


--
-- Name: interest_languages fkl5ns92tc0oithu88cu6ncqfk9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interest_languages
    ADD CONSTRAINT fkl5ns92tc0oithu88cu6ncqfk9 FOREIGN KEY (interest_id) REFERENCES public.interests(user_id);


--
-- Name: document_metadata fkmw6goytcnfvwqcjw4o7kfcbr6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_metadata
    ADD CONSTRAINT fkmw6goytcnfvwqcjw4o7kfcbr6 FOREIGN KEY (course_id) REFERENCES public.courses(course_id);


--
-- Name: document_metadata fkpjrxiuo0ka22kh1d0bcaph8mm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_metadata
    ADD CONSTRAINT fkpjrxiuo0ka22kh1d0bcaph8mm FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: interests fkq9kr60l7n7h3yf82s44rkoe4g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interests
    ADD CONSTRAINT fkq9kr60l7n7h3yf82s44rkoe4g FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: course_grades fkr8k00lkadqwsing5flsyt5pwb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_grades
    ADD CONSTRAINT fkr8k00lkadqwsing5flsyt5pwb FOREIGN KEY (enrollment_id) REFERENCES public.enrollment(enrollmentid);


--
-- PostgreSQL database dump complete
--

\unrestrict sjw8gaiQvPMjQ3UzYmeCWsPJv4Sp6Z7An4euLAFCkWAiStZsSdaa7l9vT4Oh2ke

