spring.application.name=backend

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion-cursos-backend
spring.datasource.username=postgres
spring.datasource.password=1Ljp1407+

# Estrategia de creación de tablas (usa 'update' para no borrar datos o 'create' para limpiar)
spring.jpa.hibernate.ddl-auto=update

# Mostrar el SQL generado por Hibernate en la consola
spring.jpa.show-sql=true

# Formatear el SQL para una mejor legibilidad 
spring.jpa.properties.hibernate.format_sql=true

# Configurar el dialecto de Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuración de logging para mostrar los parámetros de las consultas SQL
logging.level.org.hibernate.orm.jdbc.bind=trace
